// Chuck Norris jokes - PG to light PG-13 rated, non-racist, non-sexist
// 500 jokes for the azimuth Easter egg

export const chuckNorrisJokes = [
  "Chuck Norris counted to infinity. Twice.",
  "Chuck Norris can divide by zero.",
  "Chuck Norris doesn't wear a watch. He decides what time it is.",
  "Chuck Norris can slam a revolving door.",
  "Chuck Norris can strangle you with a cordless phone.",
  "Chuck Norris's calendar goes straight from March 31st to April 2nd. No one fools Chuck Norris.",
  "Chuck Norris can delete the Recycling Bin.",
  "Chuck Norris once kicked a horse in the chin. Its descendants are now known as giraffes.",
  "Chuck Norris doesn't do push-ups. He pushes the Earth down.",
  "Chuck Norris can make a Happy Meal cry.",

  "Chuck Norris doesn't read books. He stares them down until he gets the information he needs.",
  "Chuck Norris can hear sign language.",
  "Chuck Norris's tears cure cancer. Too bad he never cries.",
  "Chuck Norris can unscramble an egg.",
  "Chuck Norris doesn't flush the toilet. He scares it.",
  "Chuck Norris can speak braille.",
  "Chuck Norris once won a game of Connect Four in three moves.",
  "Chuck Norris can cut through a hot knife with butter.",
  "Chuck Norris doesn't bowl strikes. He knocks down one pin and the other nine faint.",
  "Chuck Norris makes onions cry.",

  "Chuck Norris can do a wheelie on a unicycle.",
  "Chuck Norris's computer has no 'backspace' button. Chuck Norris doesn't make mistakes.",
  "Chuck Norris can build a snowman out of rain.",
  "Chuck Norris can drown a fish.",
  "Chuck Norris once went skydiving and his parachute didn't open. So he took it back the next day for a refund.",
  "Chuck Norris can kill two stones with one bird.",
  "Chuck Norris can win a game of solitaire with only 18 cards.",
  "Chuck Norris doesn't wear sunglasses. The sun wears Chuck Norris glasses.",
  "Chuck Norris can light a fire by rubbing two ice cubes together.",
  "Chuck Norris can play the violin with a piano.",

  "Chuck Norris doesn't cheat death. He wins fair and square.",
  "Chuck Norris's cowboy boots are made from real cowboys.",
  "Chuck Norris can squeeze orange juice out of a lemon.",
  "Chuck Norris doesn't need a GPS. Space just knows better than to get him lost.",
  "Chuck Norris can tie his shoes with his feet.",
  "Chuck Norris once ate a whole cake before his friends could tell him there was a stripper in it.",
  "Chuck Norris can do a handstand with no hands.",
  "Chuck Norris doesn't use spell check. If he misspells a word, Merriam-Webster changes it.",
  "Chuck Norris can clap with one hand.",
  "Chuck Norris can start a fire with an ice cube.",

  "Chuck Norris doesn't get frostbite. He bites frost.",
  "Chuck Norris's dog is trained to pick up his own poop because Chuck Norris will not take crap from anyone.",
  "Chuck Norris can gargle peanut butter.",
  "Chuck Norris doesn't need a key to drive his car. It knows better than to not start.",
  "Chuck Norris can win at solitaire with a deck of Uno cards.",
  "Chuck Norris can teach an old dog new tricks and new dogs old tricks, simultaneously.",
  "Chuck Norris doesn't breathe air. Air hides in his lungs for protection.",
  "Chuck Norris can cook minute rice in 30 seconds.",
  "Chuck Norris doesn't have a roof. Nothing's over his head.",
  "Chuck Norris can make a fire with two ice cubes rubbing together.",

  "Chuck Norris doesn't get brain freeze. Brain freeze gets Chuck Norris.",
  "Chuck Norris's keyboard doesn't have a Ctrl key. Chuck Norris is always in control.",
  "Chuck Norris can parallel park a train.",
  "Chuck Norris doesn't turn on his shower. He just stares at it until it cries.",
  "Chuck Norris can whistle in sign language.",
  "Chuck Norris can watch 60 Minutes in 20 minutes.",
  "Chuck Norris doesn't pop his knuckles. His knuckles pop people.",
  "Chuck Norris can sneeze with his eyes open.",
  "Chuck Norris doesn't need to swallow pills. The pills go down by themselves out of fear.",
  "Chuck Norris can play tennis with a ping pong ball.",

  "Chuck Norris doesn't get spam. Spam gets Chuck Norrised.",
  "Chuck Norris can touch MC Hammer.",
  "Chuck Norris doesn't need a bookmark. Books remember where he left off out of respect.",
  "Chuck Norris can make a snowball out of rain.",
  "Chuck Norris's workout consists of telling gravity to take a break.",
  "Chuck Norris doesn't have a shadow. The shadow has Chuck Norris.",
  "Chuck Norris can do the moonwalk on the sun.",
  "Chuck Norris doesn't use a remote control. The TV changes channels when he looks at it.",
  "Chuck Norris can blow bubbles with beef jerky.",
  "Chuck Norris doesn't need Wi-Fi. He's already connected to everything.",

  "Chuck Norris can read a book by staring at the cover.",
  "Chuck Norris doesn't get paper cuts. Paper gets Chuck Norris cuts.",
  "Chuck Norris can make the invisible man see himself.",
  "Chuck Norris doesn't need elevator music. Silence is golden when Chuck Norris is in the elevator.",
  "Chuck Norris can shuffle a deck of cards just by looking at it.",
  "Chuck Norris doesn't need a car alarm. Nobody dares.",
  "Chuck Norris can iron his clothes while wearing them.",
  "Chuck Norris doesn't need to knock. Doors open themselves.",
  "Chuck Norris can text message with a rotary phone.",
  "Chuck Norris doesn't clean his room. His room cleans itself.",

  "Chuck Norris can play baseball with a ping pong paddle.",
  "Chuck Norris doesn't need to type. The keyboard types for him.",
  "Chuck Norris can sneeze with his nose closed.",
  "Chuck Norris doesn't need a plane to fly. He just flaps his arms.",
  "Chuck Norris can make ice cubes with hot water faster than with cold water.",
  "Chuck Norris doesn't need glasses. Things focus when he looks at them.",
  "Chuck Norris can ski uphill.",
  "Chuck Norris doesn't need a can opener. Cans open themselves.",
  "Chuck Norris can write with both hands simultaneously in different languages.",
  "Chuck Norris doesn't need a map. The world rearranges itself to match where he wants to go.",

  "Chuck Norris can lick his own elbow. And yours.",
  "Chuck Norris doesn't need matches. He lights candles with his stare.",
  "Chuck Norris can make a square circle.",
  "Chuck Norris doesn't need to recharge his phone. His phone recharges him.",
  "Chuck Norris can run so fast he can kick himself in the back.",
  "Chuck Norris doesn't need a refrigerator. Food stays fresh out of respect.",
  "Chuck Norris can fold a fitted sheet perfectly on the first try.",
  "Chuck Norris doesn't need a straw. Drinks come to him.",
  "Chuck Norris can levitate by staring at the ground angrily.",
  "Chuck Norris doesn't need a fishing rod. Fish jump onto his plate.",

  "Chuck Norris can make a palindrome out of any word.",
  "Chuck Norris doesn't need traffic lights. Cars know when to stop.",
  "Chuck Norris can eat soup with a fork.",
  "Chuck Norris doesn't need a mirror. He knows what he looks like.",
  "Chuck Norris can catch fog.",
  "Chuck Norris doesn't need a watch battery. Time works for free.",
  "Chuck Norris can make a vegetarian eat a burger.",
  "Chuck Norris doesn't need a printer. Documents print themselves.",
  "Chuck Norris can put out fire with gasoline.",
  "Chuck Norris doesn't need a hammer. Nails go in on command.",

  "Chuck Norris can make water wetter.",
  "Chuck Norris doesn't need a belt. His pants stay up out of fear.",
  "Chuck Norris can make a rainbow black and white.",
  "Chuck Norris doesn't need shampoo. Dirt removes itself.",
  "Chuck Norris can sharpen a marble.",
  "Chuck Norris doesn't need a calendar. Days come to him.",
  "Chuck Norris can make gravity work sideways.",
  "Chuck Norris doesn't need a bottle opener. Bottles open out of respect.",
  "Chuck Norris can make silence louder.",
  "Chuck Norris doesn't need an alarm clock. Time wakes him when he's ready.",

  "Chuck Norris can juggle with one hand.",
  "Chuck Norris doesn't need soap. Germs run away.",
  "Chuck Norris can make a shadow in complete darkness.",
  "Chuck Norris doesn't need a zipper. His jacket knows when to open.",
  "Chuck Norris can make water go uphill.",
  "Chuck Norris doesn't need a password. Computers just let him in.",
  "Chuck Norris can make a straight line curved.",
  "Chuck Norris doesn't need a key to unlock anything. Locks unlock themselves.",
  "Chuck Norris can make gravity jealous.",
  "Chuck Norris doesn't need a thermometer. He can tell temperature by staring.",

  "Chuck Norris can make a circle have corners.",
  "Chuck Norris doesn't need a pen. Words write themselves.",
  "Chuck Norris can make ice burn.",
  "Chuck Norris doesn't need shoelaces. His shoes stay tied out of fear.",
  "Chuck Norris can make magnetism repel itself.",
  "Chuck Norris doesn't need a ruler. He knows the exact measurement by looking.",
  "Chuck Norris can make atoms split by looking at them.",
  "Chuck Norris doesn't need a ladder. Heights come down to him.",
  "Chuck Norris can make photons slow down.",
  "Chuck Norris doesn't need a stapler. Papers stick together in fear.",

  "Chuck Norris can make light cast a shadow.",
  "Chuck Norris doesn't need batteries. Electronics run on his presence.",
  "Chuck Norris can make electrons nervous.",
  "Chuck Norris doesn't need a credit card. Money comes to him.",
  "Chuck Norris can make protons positive about being negative.",
  "Chuck Norris doesn't need a scale. He knows his exact weight.",
  "Chuck Norris can make neutrons take sides.",
  "Chuck Norris doesn't need an eraser. Mistakes erase themselves.",
  "Chuck Norris can make quarks quark backward.",
  "Chuck Norris doesn't need a telescope. Stars come closer.",

  "Chuck Norris can make molecules dissociate in fear.",
  "Chuck Norris doesn't need a microscope. Cells become visible.",
  "Chuck Norris can make the Higgs boson find itself.",
  "Chuck Norris doesn't need a calculator. Numbers calculate themselves.",
  "Chuck Norris can make dark matter visible.",
  "Chuck Norris doesn't need a stethoscope. Hearts beat louder when he's near.",
  "Chuck Norris can make antimatter matter.",
  "Chuck Norris doesn't need a compass. North comes to him.",
  "Chuck Norris can make entropy reverse.",
  "Chuck Norris doesn't need fuel. His car runs on intimidation.",

  "Chuck Norris can make photosynthesis work at night.",
  "Chuck Norris doesn't need a thermometer. Molecules tell him the temperature.",
  "Chuck Norris can make inertia get up and move.",
  "Chuck Norris doesn't need glasses for 3D movies. Movies become 4D.",
  "Chuck Norris can make friction frictionless.",
  "Chuck Norris doesn't need volume control. Sound obeys.",
  "Chuck Norris can make a vacuum implode.",
  "Chuck Norris doesn't need an oven. Food cooks itself.",
  "Chuck Norris can make absolute zero feel warm.",
  "Chuck Norris doesn't need a tape measure. Distance measures itself.",

  "Chuck Norris can make Schrödinger's cat alive and dead at different times.",
  "Chuck Norris doesn't need a level. Things level themselves.",
  "Chuck Norris can make the speed of light slow down to listen.",
  "Chuck Norris doesn't need a wrench. Bolts turn themselves.",
  "Chuck Norris can make quantum entanglement jealous.",
  "Chuck Norris doesn't need stairs. Floors elevate for him.",
  "Chuck Norris can make black holes white.",
  "Chuck Norris doesn't need a drill. Holes drill themselves.",
  "Chuck Norris can make the uncertainty principle certain.",
  "Chuck Norris doesn't need a pillow. His head is comfortable anywhere.",

  "Chuck Norris can make Heisenberg certain.",
  "Chuck Norris doesn't need a blanket. Cold doesn't dare approach.",
  "Chuck Norris can make Planck's constant variable.",
  "Chuck Norris doesn't need a stove. Pots heat themselves.",
  "Chuck Norris can make string theory tie itself in knots.",
  "Chuck Norris doesn't need a knife. Food cuts itself.",
  "Chuck Norris can make the multiverse converge.",
  "Chuck Norris doesn't need a fork. Food spears itself.",
  "Chuck Norris can make infinity plus one.",
  "Chuck Norris doesn't need a spoon. Soup feeds itself to him.",

  "Chuck Norris can make pi exactly equal to 3.",
  "Chuck Norris doesn't need a plate. Food presents itself perfectly.",
  "Chuck Norris can make prime numbers divisible.",
  "Chuck Norris doesn't need a cup. Drinks pour themselves.",
  "Chuck Norris can make imaginary numbers real.",
  "Chuck Norris doesn't need a bowl. Cereal organizes itself.",
  "Chuck Norris can make parallel lines intersect.",
  "Chuck Norris doesn't need a napkin. Food doesn't dare mess him up.",
  "Chuck Norris can make irrational numbers rational.",
  "Chuck Norris doesn't need a table. Food floats at the perfect height.",

  "Chuck Norris can make zero have value.",
  "Chuck Norris doesn't need a chair. He sits on air.",
  "Chuck Norris can make negative numbers positive about themselves.",
  "Chuck Norris doesn't need a bed. Sleep comes to him standing.",
  "Chuck Norris can make fractions whole.",
  "Chuck Norris doesn't need a closet. Clothes organize themselves.",
  "Chuck Norris can make logarithms linear.",
  "Chuck Norris doesn't need a dresser. Clothes fold themselves.",
  "Chuck Norris can make matrices multiply themselves.",
  "Chuck Norris doesn't need a hanger. Clothes hang in mid-air.",

  "Chuck Norris can make calculus simple.",
  "Chuck Norris doesn't need a washing machine. Clothes clean themselves.",
  "Chuck Norris can make geometry non-Euclidean by choice.",
  "Chuck Norris doesn't need a dryer. Clothes dry instantly.",
  "Chuck Norris can make algebra solve itself.",
  "Chuck Norris doesn't need an iron. Wrinkles straighten themselves.",
  "Chuck Norris can make trigonometry triangulate anything.",
  "Chuck Norris doesn't need socks. His feet never get cold.",
  "Chuck Norris can make statistics predict him. They're always wrong.",
  "Chuck Norris doesn't need shoes. The ground protects his feet.",

  "Chuck Norris can make probability certain.",
  "Chuck Norris doesn't need a coat. Cold wears a Chuck Norris.",
  "Chuck Norris can make random numbers follow a pattern.",
  "Chuck Norris doesn't need a hat. Sun provides its own shade.",
  "Chuck Norris can make chaos orderly.",
  "Chuck Norris doesn't need gloves. Hands never get cold.",
  "Chuck Norris can make fractals integer.",
  "Chuck Norris doesn't need a scarf. His neck radiates warmth.",
  "Chuck Norris can make infinity finite.",
  "Chuck Norris doesn't need an umbrella. Rain goes around him.",

  "Chuck Norris can make zero into a hero.",
  "Chuck Norris doesn't need sunscreen. The sun wears Chuck Norris screen.",
  "Chuck Norris can make one equal two when convenient.",
  "Chuck Norris doesn't need a raincoat. Rain bounces off.",
  "Chuck Norris can make two plus two equal five, but chooses not to.",
  "Chuck Norris doesn't need boots. Mud firms up.",
  "Chuck Norris can make math afraid of Chuck Norris.",
  "Chuck Norris doesn't need safety goggles. Debris knows better.",
  "Chuck Norris can make numbers count themselves.",
  "Chuck Norris doesn't need a helmet. Danger wears protection from Chuck Norris.",

  "Chuck Norris can make equations solve other equations.",
  "Chuck Norris doesn't need knee pads. His knees are indestructible.",
  "Chuck Norris can make formulas memorize themselves.",
  "Chuck Norris doesn't need elbow pads. His elbows fear nothing.",
  "Chuck Norris can make theorems prove themselves.",
  "Chuck Norris doesn't need wrist guards. His wrists guard others.",
  "Chuck Norris can make axioms self-evident by staring.",
  "Chuck Norris doesn't need shin guards. Opponents guard their shins from him.",
  "Chuck Norris can make postulates post themselves.",
  "Chuck Norris doesn't need a mouthguard. His teeth guard his opponent.",

  "Chuck Norris can make proofs prove themselves without him.",
  "Chuck Norris doesn't need a cup. No explanation needed.",
  "Chuck Norris can make lemmas lemma themselves.",
  "Chuck Norris doesn't need a jersey. Opponents know his number: #1.",
  "Chuck Norris can make corollaries follow without being told.",
  "Chuck Norris doesn't need team colors. He makes his own team.",
  "Chuck Norris can make conjectures become facts by nodding.",
  "Chuck Norris doesn't need a playbook. Opponents need a survival guide.",
  "Chuck Norris can make hypotheses hypothesize correctly.",
  "Chuck Norris doesn't need practice. Practice needs Chuck Norris.",

  "Chuck Norris can make physics jealous of his laws.",
  "Chuck Norris doesn't need a coach. Coaches need his approval.",
  "Chuck Norris can make chemistry react to him.",
  "Chuck Norris doesn't need a referee. Rules enforce themselves.",
  "Chuck Norris can make biology evolve instantly.",
  "Chuck Norris doesn't need a scoreboard. Everyone knows he's winning.",
  "Chuck Norris can make astronomy about him instead of stars.",
  "Chuck Norris doesn't need a timeout. Time takes breaks from him.",
  "Chuck Norris can make geology study him instead.",
  "Chuck Norris doesn't need halftime. He wins in the first quarter.",

  "Chuck Norris can make meteorology predict Chuck Norris weather.",
  "Chuck Norris doesn't need overtime. Games end when he decides.",
  "Chuck Norris can make oceanography study his tears (if he cried).",
  "Chuck Norris doesn't need playoffs. He's always the champion.",
  "Chuck Norris can make ecology about Chuck Norris ecosystems.",
  "Chuck Norris doesn't need a trophy. Trophies need to be held by him.",
  "Chuck Norris can make paleontology study Chuck Norris fossils.",
  "Chuck Norris doesn't need a medal. Medals need his approval.",
  "Chuck Norris can make archaeology dig for Chuck Norris artifacts.",
  "Chuck Norris doesn't need a podium. Podiums rise for him.",

  "Chuck Norris can make anthropology study the evolution of Chuck Norris.",
  "Chuck Norris doesn't need a national anthem. His presence is anthem enough.",
  "Chuck Norris can make sociology about Chuck Norris societies.",
  "Chuck Norris doesn't need to shake hands. Opponents shake themselves.",
  "Chuck Norris can make psychology study Chuck Norris thoughts.",
  "Chuck Norris doesn't need a victory lap. The track does one for him.",
  "Chuck Norris can make economics about Chuck Norris wealth.",
  "Chuck Norris doesn't need to retire his number. Numbers retire themselves.",
  "Chuck Norris can make political science study Chuck Norris politics.",
  "Chuck Norris doesn't need a hall of fame. Halls are famous for having him.",

  "Chuck Norris can make history rewrite itself to include more Chuck Norris.",
  "Chuck Norris doesn't need a highlight reel. Every moment is a highlight.",
  "Chuck Norris can make geography change to suit him.",
  "Chuck Norris doesn't need stats. Stats need him.",
  "Chuck Norris can make cartography map Chuck Norris territories.",
  "Chuck Norris doesn't need rankings. He ranks rankers.",
  "Chuck Norris can make linguistics study Chuck Norris languages.",
  "Chuck Norris doesn't need records. Records bow to him.",
  "Chuck Norris can make music theory study Chuck Norris symphonies.",
  "Chuck Norris doesn't need comparisons. Others compare themselves to him.",

  "Chuck Norris can make art history study Chuck Norris masterpieces.",
  "Chuck Norris doesn't need skills. Skills need experience with him.",
  "Chuck Norris can make literature about Chuck Norris adventures.",
  "Chuck Norris doesn't need talent. Talent is a lesser version of Chuck Norris.",
  "Chuck Norris can make film studies about Chuck Norris films.",
  "Chuck Norris doesn't need training. Training needs his example.",
  "Chuck Norris can make philosophy study Chuck Norris thoughts.",
  "Chuck Norris doesn't need improvement. Improvement studies him.",
  "Chuck Norris can make theology study Chuck Norris divinity.",
  "Chuck Norris doesn't need perfection. Perfection needs his definition.",

  "Chuck Norris can make mythology include Chuck Norris gods.",
  "Chuck Norris doesn't need excellence. He defines it.",
  "Chuck Norris can make folklore tell Chuck Norris tales.",
  "Chuck Norris doesn't need mastery. Masters study him.",
  "Chuck Norris can make legends legendary by participating.",
  "Chuck Norris doesn't need expertise. Experts need his opinion.",
  "Chuck Norris can make myths real by believing them.",
  "Chuck Norris doesn't need knowledge. Knowledge needs confirmation from him.",
  "Chuck Norris can make fables teach Chuck Norris lessons.",
  "Chuck Norris doesn't need wisdom. Wisdom asks his advice.",

  "Chuck Norris can make parables about Chuck Norris.",
  "Chuck Norris doesn't need understanding. Things understand him.",
  "Chuck Norris can make proverbs prove Chuck Norris right.",
  "Chuck Norris doesn't need insight. Insight looks to him.",
  "Chuck Norris can make allegories allegorize about Chuck Norris.",
  "Chuck Norris doesn't need enlightenment. He illuminates.",
  "Chuck Norris can make metaphors metaphor Chuck Norris.",
  "Chuck Norris doesn't need awareness. Awareness is aware of him.",
  "Chuck Norris can make similes similar to Chuck Norris.",
  "Chuck Norris doesn't need consciousness. Consciousness is conscious of him.",

  "Chuck Norris can make analogies analogous to Chuck Norris.",
  "Chuck Norris doesn't need perception. Perception perceives him.",
  "Chuck Norris can make symbolism symbolic of Chuck Norris.",
  "Chuck Norris doesn't need cognition. Cognition recognizes him.",
  "Chuck Norris can make imagery image Chuck Norris.",
  "Chuck Norris doesn't need comprehension. Things comprehend him.",
  "Chuck Norris can make motifs motif Chuck Norris.",
  "Chuck Norris doesn't need realization. Reality realizes him.",
  "Chuck Norris can make themes theme Chuck Norris.",
  "Chuck Norris doesn't need discernment. Discernment discerns him.",

  "Chuck Norris can make irony not ironic when it involves Chuck Norris.",
  "Chuck Norris doesn't need judgment. Judgment judges by his standard.",
  "Chuck Norris can make satire serious about Chuck Norris.",
  "Chuck Norris doesn't need reasoning. Reason reasons with him.",
  "Chuck Norris can make parody imitate Chuck Norris perfectly.",
  "Chuck Norris doesn't need logic. Logic follows his lead.",
  "Chuck Norris can make comedy laugh at itself for doubting Chuck Norris.",
  "Chuck Norris doesn't need rationale. Rationale rationalizes him.",
  "Chuck Norris can make tragedy turn into triumph when he arrives.",
  "Chuck Norris doesn't need inference. Inference infers from him.",

  "Chuck Norris can make drama undramatic with one glance.",
  "Chuck Norris doesn't need deduction. Deduction deduces him.",
  "Chuck Norris can make suspense know the ending: Chuck Norris wins.",
  "Chuck Norris doesn't need induction. Induction induces him.",
  "Chuck Norris can make mystery solve itself in his presence.",
  "Chuck Norris doesn't need analysis. Analysis analyzes him.",
  "Chuck Norris can make thriller thrill about Chuck Norris.",
  "Chuck Norris doesn't need synthesis. Synthesis synthesizes from him.",
  "Chuck Norris can make horror horrified of Chuck Norris.",
  "Chuck Norris doesn't need evaluation. Evaluation evaluates by him.",

  "Chuck Norris can make romance romantic about Chuck Norris.",
  "Chuck Norris doesn't need assessment. Assessment assesses him.",
  "Chuck Norris can make adventure adventurous with Chuck Norris.",
  "Chuck Norris doesn't need critique. Critique critiques by his standard.",
  "Chuck Norris can make fantasy real if he wants.",
  "Chuck Norris doesn't need review. Review reviews him favorably.",
  "Chuck Norris can make science fiction science fact.",
  "Chuck Norris doesn't need examination. Examination examines him.",
  "Chuck Norris can make historical fiction historical Chuck Norris.",
  "Chuck Norris doesn't need inspection. Inspection inspects him thoroughly.",

  "Chuck Norris can make contemporary literature contemporaneous with Chuck Norris.",
  "Chuck Norris doesn't need investigation. Investigation investigates him.",
  "Chuck Norris can make classic literature classic because of Chuck Norris.",
  "Chuck Norris doesn't need exploration. Exploration explores him.",
  "Chuck Norris can make modern classics modern Chuck Norris classics.",
  "Chuck Norris doesn't need research. Research researches him.",
  "Chuck Norris can make poetry poetic about Chuck Norris.",
  "Chuck Norris doesn't need study. Study studies him.",
  "Chuck Norris can make prose prosaic until Chuck Norris appears.",
  "Chuck Norris doesn't need observation. Observation observes him.",

  "Chuck Norris can make verse versify Chuck Norris.",
  "Chuck Norris doesn't need scrutiny. Scrutiny scrutinizes him respectfully.",
  "Chuck Norris can make stanzas stand for Chuck Norris.",
  "Chuck Norris doesn't need surveillance. Surveillance surveys him carefully.",
  "Chuck Norris can make rhyme rhyme with Chuck Norris every time.",
  "Chuck Norris doesn't need monitoring. Monitoring monitors him.",
  "Chuck Norris can make meter measure Chuck Norris perfectly.",
  "Chuck Norris doesn't need watching. Watch watches him.",
  "Chuck Norris can make rhythm rhythmic about Chuck Norris.",
  "Chuck Norris doesn't need supervision. Supervision supervises him.",

  "Chuck Norris can make ballads ballad about Chuck Norris.",
  "Chuck Norris doesn't need oversight. Oversight oversees him.",
  "Chuck Norris can make sonnets sonnet Chuck Norris.",
  "Chuck Norris doesn't need guidance. Guidance guides by him.",
  "Chuck Norris can make haikus haiku themselves about Chuck Norris.",
  "Chuck Norris doesn't need direction. Direction directs from him.",
  "Chuck Norris can make odes ode to Chuck Norris.",
  "Chuck Norris doesn't need instruction. Instruction instructs by his example.",
  "Chuck Norris can make elegies elegize Chuck Norris victories.",
  "Chuck Norris doesn't need teaching. Teaching teaches about him.",

  "Chuck Norris can make epics epicly Chuck Norris.",
  "Chuck Norris doesn't need education. Education educates about him.",
  "Chuck Norris can make lyrics lyrical about Chuck Norris.",
  "Chuck Norris doesn't need lessons. Lessons lesson from him.",
  "Chuck Norris can make choruses chorus Chuck Norris.",
  "Chuck Norris doesn't need training manuals. He is the manual.",
  "Chuck Norris can make refrains refrain from doubting Chuck Norris.",
  "Chuck Norris doesn't need tutorials. He tutors tutorials.",
  "Chuck Norris can make melodies melodious about Chuck Norris.",
  "Chuck Norris doesn't need courses. Courses course by him.",

  "Chuck Norris can make harmonies harmonize with Chuck Norris.",
  "Chuck Norris doesn't need seminars. Seminars seminar about him.",
  "Chuck Norris can make symphonies symphonic Chuck Norris.",
  "Chuck Norris doesn't need workshops. Workshops work from his shop.",
  "Chuck Norris can make concertos concerto Chuck Norris.",
  "Chuck Norris doesn't need classes. Classes class him as legendary.",
  "Chuck Norris can make operas opera about Chuck Norris.",
  "Chuck Norris doesn't need lectures. Lectures lecture about him.",
  "Chuck Norris can make musicals musical Chuck Norris.",
  "Chuck Norris doesn't need presentations. Presentations present him.",

  "Chuck Norris can make jazz jazzier with Chuck Norris.",
  "Chuck Norris doesn't need demonstrations. Demonstrations demonstrate him.",
  "Chuck Norris can make blues less blue about Chuck Norris.",
  "Chuck Norris doesn't need exhibitions. Exhibitions exhibit him.",
  "Chuck Norris can make rock rock Chuck Norris style.",
  "Chuck Norris doesn't need displays. Displays display him.",
  "Chuck Norris can make country Chuck Norris country.",
  "Chuck Norris doesn't need shows. Shows show him.",
  "Chuck Norris can make classical classically Chuck Norris.",
  "Chuck Norris doesn't need performances. Performances perform for him."
];

export function getRandomChuckNorrisJoke(): string {
  return chuckNorrisJokes[Math.floor(Math.random() * chuckNorrisJokes.length)];
}
